backend:
  name: git-gateway
  branch: deploy

media_folder: "static/images/uploads" # Storage for media files
public_folder: "/images/uploads"

collections:
  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
    slug: "{{month}}-{{day}}-{{year}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Feature Image", name: "image", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Author", name: "author", widget: "string", default: "Felix Jen"}
      - {label: "Draft", name: "draft", widget: "boolean", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: "note"
    label: "Note"
    folder: "content/note"
    create: true
    slug: "{{month}}-{{day}}-{{year}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Feature Image", name: "image", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Author", name: "author", widget: "string", default: "Felix Jen"}
      - {label: "Draft", name: "draft", widget: "boolean", required: false}
      - {label: "Body", name: "body", widget: "markdown"}